#spring.application.name=eureka
#http://eureka-server:8761/eureka/
#
#server.port=8761
##eureka.instance.hostname=localhost
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false


spring.application.name=eureka
server.port=8761

# Eureka Server DOES NOT register itself
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false

# Optional (hostname for other services)
eureka.instance.hostname=eureka-server
